# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [10]:
pokemon = pd.read_csv('/content/pokemon.csv')

### Step 3. Assign it to a variable called pokemon

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

In [11]:
display(pokemon.head())

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [12]:
cols_to_front = ['Name', 'Type 1', 'HP']

cols_to_front = [col for col in cols_to_front if col in pokemon.columns]

remaining_cols = [col for col in pokemon.columns if col not in cols_to_front]
pokemon = pokemon[cols_to_front + remaining_cols]
display(pokemon.head())

,Name,Type 1,HP,#,Type 2,Total,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,1,Poison,318,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,2,Poison,405,62,63,80,80,60,1,False
2,Venusaur,Grass,80,3,Poison,525,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,3,Poison,625,100,123,122,120,80,1,False
4,Charmander,Fire,39,4,NaN,309,52,43,60,50,65,1,False

### Step 5. Add another column called place, and insert what you have in mind.

In [13]:
places = ['forest', 'volcano', 'river', 'forest']
pokemon.loc[:, 'place'] = places * (len(pokemon) // len(places))
display(pokemon.head())

,Name,Type 1,HP,#,Type 2,Total,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,place
0,Bulbasaur,Grass,45,1,Poison,318,49,49,65,65,45,1,False,forest
1,Ivysaur,Grass,60,2,Poison,405,62,63,80,80,60,1,False,volcano
2,Venusaur,Grass,80,3,Poison,525,82,83,100,100,80,1,False,river
3,VenusaurMega Venusaur,Grass,80,3,Poison,625,100,123,122,120,80,1,False,forest
4,Charmander,Fire,39,4,NaN,309,52,43,60,50,65,1,False,forest

### Step 6. Present the type of each column

In [14]:
print(pokemon.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        800 non-null    object
 1   Type 1      800 non-null    object
 2   HP          800 non-null    int64
 3   #           800 non-null    int64
 4   Type 2      414 non-null    object
 5   Total       800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
 13  place       800 non-null    object
dtypes: bool(1), int64(9), object(4)
memory usage: 82.2+ KB
None

### BONUS: Create your own question and answer it.