# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv')

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [3]:
df = df.loc[:, 'school':'guardian']

### Step 5. Create a lambda function that will capitalize strings.

In [4]:
capitalizer = lambda x: x.upper()

### Step 6. Capitalize both Mjob and Fjob

In [5]:
df['Mjob'] = df['Mjob'].apply(capitalizer)
df['Fjob'] = df['Fjob'].apply(capitalizer)

### Step 7. Print the last elements of the data set.

In [6]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
390,MS,M,20,U,LE3,A,2,2,SERVICES,SERVICES,course,other
391,MS,M,17,U,LE3,T,3,1,SERVICES,SERVICES,course,mother
392,MS,M,21,R,GT3,T,1,1,OTHER,OTHER,course,other
393,MS,M,18,R,LE3,T,3,2,SERVICES,OTHER,course,mother
394,MS,M,19,U,LE3,T,1,1,OTHER,AT_HOME,course,father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [7]:
display(df[['Mjob', 'Fjob']].head())

      Mjob      Fjob
0  AT_HOME   TEACHER
1  AT_HOME     OTHER
2  AT_HOME     OTHER
3   HEALTH  SERVICES
4    OTHER     OTHER

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [8]:
def majority(age):
    return True if age > 17 else False

df['legal_drinker'] = df['age'].apply(majority)

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [9]:
df_numeric = df.select_dtypes(include=['number'])
df[df_numeric.columns] = df_numeric * 10