# Wine

### Introduction:

This exercise is a adaptation from the UCI Wine dataset.
The only pupose is to practice deleting data with pandas.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data).

### Step 3. Assign it to a variable called wine

In [2]:
wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
display(wine.head())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [3]:
wine = wine.drop(columns=[0, 3, 6, 8, 10, 12, 13], axis=1)
display(wine.head())

      1     2     4    5     7     9     11
0  14.23  1.71  15.6  127  3.06  2.29  1.04
1  13.20  1.78  11.2  100  2.76  1.28  1.05
2  13.16  2.36  18.6  101  3.24  2.81  1.03
3  14.37  1.95  16.8  113  3.49  2.18  0.86
4  13.24  2.59  21.0  118  2.69  1.82  1.04

### Step 5. Assign the columns as below:

The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [4]:
wine.columns = ['alcohol', 'malic_acid', 'alcalinity_of_ash', 'magnesium', 'flavanoids', 'proanthocyanins', 'hue']
display(wine.head())

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,14.23,1.71,15.6,127,3.06,2.29,1.04
1,13.20,1.78,11.2,100,2.76,1.28,1.05
2,13.16,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86
4,13.24,2.59,21.0,118,2.69,1.82,1.04

### Step 6. Set the values of the first 3 rows from alcohol as NaN

In [5]:
import numpy as np
wine.loc[0:2, 'alcohol'] = np.nan
display(wine.head())

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127,3.06,2.29,1.04
1,NaN,1.78,11.2,100,2.76,1.28,1.05
2,NaN,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86
4,13.24,2.59,21.0,118,2.69,1.82,1.04

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [6]:
wine.loc[3:4, 'magnesium'] = np.nan
display(wine.head())

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,NaN,3.49,2.18,0.86
4,13.24,2.59,21.0,NaN,2.69,1.82,1.04

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [7]:
wine['alcohol'] = wine['alcohol'].fillna(10)
wine['magnesium'] = wine['magnesium'].fillna(100)
display(wine.head())

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.71,15.6,127.0,3.06,2.29,1.04
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
2,10.00,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
4,13.24,2.59,21.0,100.0,2.69,1.82,1.04

### Step 9. Count the number of missing values

In [8]:
missing_values = wine.isnull().sum()
display(missing_values)

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 10.  Create an array of 10 random numbers up until 10

In [9]:
random_indices = np.random.randint(0, 10, 10)
display(random_indices)

array([2, 8, 0, 0, 4, 5, 5, 2, 6, 2])

### Step 11.  Use random numbers you generated as an index and assign NaN value to each of cell.

In [10]:
import random
for r_idx in random_indices:
    random_column = random.choice(wine.columns)
    wine.loc[r_idx, random_column] = np.nan
display(wine.head(15))

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.71,15.6,127.0,NaN,2.29,1.04
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,NaN,101.0,NaN,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
4,13.24,2.59,21.0,100.0,2.69,NaN,1.04
5,14.20,1.76,NaN,NaN,3.39,1.97,1.05
6,14.39,1.87,14.6,96.0,NaN,1.98,1.02
7,14.06,2.15,17.6,121.0,2.51,1.25,1.06
8,14.83,NaN,14.0,97.0,2.98,1.98,1.08
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
10,14.10,2.16,18.0,105.0,3.32,2.38,1.25
11,14.12,1.48,16.8,95.0,2.43,1.57,1.17
12,13.75,1.73,16.0,89.0,2.76,1.81,1.15
13,14.75,1.73,11.4,91.0,3.69,2.81,1.25
14,14.38,1.87,12.0,102.0,3.64,2.96,1.20

### Step 12.  How many missing values do we have?

In [11]:
missing_values_after_random = wine.isnull().sum()
display(missing_values_after_random)

alcohol              1
malic_acid           1
alcalinity_of_ash    2
magnesium            1
flavanoids           3
proanthocyanins      1
hue                  0
dtype: int64

### Step 13. Delete the rows that contain missing values

In [12]:
wine = wine.dropna()
display(wine.head())

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
7,14.06,2.15,17.6,121.0,2.51,1.25,1.06
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
10,14.10,2.16,18.0,105.0,3.32,2.38,1.25

### Step 14. Print only the non-null values in alcohol

In [13]:
display(wine['alcohol'])

1      10.00
3      14.37
7      14.06
9      13.86
10     14.10
       ...
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: alcohol, Length: 172, dtype: float64

### Step 15.  Reset the index, so it starts with 0 again

In [14]:
wine = wine.reset_index(drop=True)
display(wine.head())

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.78,11.2,100.0,2.76,1.28,1.05
1,14.37,1.95,16.8,100.0,3.49,2.18,0.86
2,14.06,2.15,17.6,121.0,2.51,1.25,1.06
3,13.86,1.35,16.0,98.0,3.15,1.85,1.01
4,14.10,2.16,18.0,105.0,3.32,2.38,1.25

### BONUS: Create your own question and answer it.

In [16]:
average_alcohol = wine['alcohol'].mean()
average_magnesium = wine['magnesium'].mean()

print(f"Average alcohol content: {average_alcohol:.2f}")
print(f"Average magnesium content: {average_magnesium:.2f}")

Average alcohol content: 12.95
Average magnesium content: 99.36